version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    container_name: keycloak
    command: "start-dev --http-port=8180"
    ports:
      - "8180:8180"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
