logging:
  level:
    org:
      springframework: INFO    

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/keycloak-sample-realm/protocol/openid-connect/certs
