logging:
  level:
    org:
      springframework: INFO
      keycloak: DEBUG     

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/keycloak-sample-realm/protocol/openid-connect/certs
          
policy-enforcer:
  realm: keycloak-sample-realm
  auth-server-url: http://localhost:8180
  resource: security-rest-keycloak-sample-client
  credentials:
    secret: Ropn6Wr3P5fGOEc229kDN1u2VHNxOKab
